---
fpsd_database_apt_packages:
  - postgresql
  - libpq-dev
  - python-psycopg2

fpsd_database_psql_env:
  PGHOST: "{{ PGHOST }}"
  PGPORT: "{{ PGPORT }}"
  PGDATABASE: "{{ PGDATABASE }}"
  PGUSER: "{{ PGUSER }}"
  PGPASSFILE: "{{ ansible_env.HOME }}/.pgpass"

fpsd_database_raw_schema_tables:
  - create_table_crawls.sql
  - create_table_hs_history.sql
  - create_table_frontpage_examples.sql
  - create_table_frontpage_traces.sql

# Defaults to true. Set to false if you want to use a remote database. If you
# wish not to use the database at all, set the environment variable
# `ANSIBLE_ARGS="--skip-tags=database"`. If set to false you must fill out all
# vars in the field below so Ansible can still set the appropriate environment
# variables and create the PGPASSFILE for it just works™ access to your remote
# database.
fpsd_database_initialize_local_db: true
