---
- name: Update the Ubuntu image and install the packages both scripts need.
  hosts: all
  pre_tasks:
    - name: Upgrade all packages.
      apt:
        upgrade: safe
        update_cache: yes
        cache_valid_time: 86400
  roles:
    - role: common
      tags: common

- name: Install and configure dependencies for Tor.
  hosts: all
  roles:
    - role: crawler
      tags: crawler

- name: Install PostgreSQL and configure the fpsd database.
  hosts: all
  roles:
    - role: database
      tags: database
