---
- name: Update the Ubuntu image and install the packages both scripts need.
  hosts: all
  roles:
    - role: common
      tags: common

- name: Install and configure dependencies for Tor.
  hosts: all
  roles:
    - role: crawler
      tags: crawler

- name: Install the Apt and Python dependencies of the sorter script.
  hosts: all
  roles:
    - role: sorter
      tags: sorter

- name: Install PostgrSQL and configure the fpsd database.
  hosts: all
  roles:
    - role: database
      tags: database

