---
common_apt_packages:
  - aptitude # needed by Ansible for apt 'upgrade'
  - python3-pip
  - python3.5
  - tmux
  - vim
  - libpq-dev # needed to install psycopg2 

ssh_username: "{{ ansible_ssh_user }}"

crawler_project_directory: "~{{ ssh_username }}/FingerprintSecureDrop"
crawler_git_repo: "https://github.com/freedomofpress/FingerprintSecureDrop"
