---
- name: Create the test database based on fpsd.
  become: true
  become_user: postgres
  postgresql_db:
    name: "test{{ fpsd_database_psql_env.PGDATABASE }}"
    owner: "{{ fpsd_database_psql_env.PGUSER }}"
    encoding: UTF-8 
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: "{{ fpsd_database_psql_env.PGDATABASE }}"
