---
- block:
  - name: List all schemas in the fpsd database.
    command: psql -c '\dn' fpsd
    register: schemas
    always_run: true
    changed_when: false

  - name: Create the raw schema.
    command: psql -c 'CREATE SCHEMA raw;'
    when: "'raw' not in schemas.stdout"
    register: raw_schema_result

  - name: List all tables in the raw schema.
    command: psql -c '\dt raw.*'
    register: tables
    always_run: true
    changed_when: false

  - name: "Create the tables: crawls, hs_history, frontpage_examples, & frontpage_traces."
    command: psql -c '{{ lookup("file", item) }}'
    with_items: "{{ fpsd_database_raw_schema_tables }}"
    # Each file is of the form create_table_<table name>.sql, so let's extract the
    # expected table name and inspect the table list to check if it already exists.
    when: item|regex_replace('^create_table_(.*)\\.sql$', '\\1') not in tables.stdout
    register: raw_schema_tables_result

  environment: "{{ fpsd_database_psql_env }}"
