---
- name: Create fp_user PostgreSQL user.
  become: true
  become_user: postgres
  postgresql_user:
    name: fp_user
    # We don't include punctuation to avoid needing to escape ':' and '\' in the
    # PGPASSFILE
    password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits') }}"

- name: Create the PostgreSQL password file.
  become: true
  template:
    src: pgpass_conf.j2
    dest: /var/lib/postgresql/pgpass.conf
    mode: "0600"
    owner: postgres
    group: postgres

- name: Create the fpsd database.
  become: true
  become_user: postgres
  postgresql_db:
    name: fpsd
    owner: fp_user
    encoding: UTF-8 
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
