---
- include: install-apt-deps.yml
  when: fpsd_database_initialize_local_db

- include: initialize-fpsd-db.yml
  when: fpsd_database_initialize_local_db

- include: set-environment-variables.yml

- include: initialize-raw-schema.yml

- include: initialize-test-db.yml
