---
- name: Create the PostgreSQL password file for database connection.
  become: yes
  template:
    src: pgpass_conf.j2
    dest: "/home/{{ item }}/.pgpass"
    mode: "0600"
    owner: "{{ item }}"
    group: "{{ item }}"
    force: no # Don't clobber preexisting file, since it may contain auth secrets
  with_items: "{{ fpsd_database_usernames }}"

- name: Set the database environment variables in ~/.bashrc.
  become: yes
  lineinfile:
    # Overriding the value for PGPASS to use `$HOME` so it's generalized for all users.
    # The previous task wrote the pgpass file to each user's HOME, which is mandatory
    # because postgres wants the PGPASS file to be mode 600, so it can't be shared.
    line: 'export {{ item.key }}={{ "$HOME/.pgpass" if item.key == "PGPASSFILE" else item.value }}'
    regexp: '^export {{ item.key }}='
    dest: "/etc/bash.bashrc"
    mode: "0644"
  with_dict: "{{ fpsd_database_psql_env }}"
