---
- name: Create the PostgreSQL password file for database connection.
  template:
    src: pgpass_conf.j2
    dest: "{{ fpsd_database_psql_env.PGPASSFILE }}"
    mode: "0600"
    force: no # Don't clobber preexisting file, since it may contain auth secrets

- name: Set the database environment variables in ~/.bashrc.
  lineinfile:
    line: 'export {{ item.key }}={{ item.value }}'
    regexp: '^export {{ item.key }}='
    dest: "~{{ ansible_user }}/.bashrc"
    mode: "0644"
  with_dict: "{{ fpsd_database_psql_env }}"
