---
- name: Test if a PostgreSQL password file is present.
  stat:
    path: "~{{ ansible_user }}/.pgpass"
  register: password_file
  changed_when: false
  
- name: Create the PostgreSQL password file for a local database.
  template:
    src: pgpass_conf.j2
    dest: "{{ psql_env.PGPASSFILE }}"
    mode: "0600"
  when: not password_file.stat.exists

- name: Set the database environment variables in ~/.bashrc.
  lineinfile:
    line: 'export {{ item.key }}={{ item.value }}'
    regexp: '^export {{ item.key }}='
    dest: "~{{ ansible_user }}/.bashrc"
    mode: "0644"
  with_dict: "{{ psql_env }}"
