---
hs_crawler_apt_packages:
  - xvfb # tbs
  - git #tbs
  - gnupg-curl # needed for https keyservers
  - libfontconfig1 # tbb (firefox)
  - libxrender1 # tbb (firefox)
  - libasound2 # tbb (firefox)
  - libdbus-glib-1-2 # tbb (firefox)
  - libgtk2.0-0 # tbb (firefox)

tbb_arch: 64
tbb_release: 6.0.1
tbb_locale: en-US

tor_release: 0.2.7.6

ssh_username: "{{ ansible_ssh_user }}"

hs_crawler_project_directory: "~{{ ssh_username }}/FingerprintSecureDrop"
hs_crawler_git_repo: "https://github.com/freedomofpress/FingerprintSecureDrop"
