---
# General system dependencies requiring for running
# Tor Browser Bundle (tbb).
fpsd_crawler_apt_packages:
  - aptitude # needed by Ansible for apt 'upgrade'
  - git #tbs
  - gnupg-curl # needed for https keyservers
  - libasound2 # tbb (firefox)
  - libdbus-glib-1-2 # tbb (firefox)
  - libfontconfig1 # tbb (firefox)
  - libgtk2.0-0 # tbb (firefox)
  - libpq-dev # needed to install psycopg2
  - libxrender1 # tbb (firefox)
  - python3-pip
  - python3.5
  - tmux
  - vim
  - xvfb # tbs

# General Python tooling for development. Specific Python dependencies
# for the crawler code are installed from `requirements.txt` files.
fpsd_crawler_pypi_packages:
  - pip
  - pytest
  - ipython
  - ipdb

# Specify TBB version to download and install
fpsd_crawler_tbb_release: 6.0.5
fpsd_crawler_tbb_locale: en-US
fpsd_crawler_tbb_arch: 64

# Specify Tor version to download, patch, build, and install
fpsd_crawler_tor_release: 0.2.8.7

# Clone the git repo by default, but allow disabling, e.g. in vagrant,
# where it can be mounted in.
fpsd_crawler_clone_git_repo: true
fpsd_crawler_project_directory: "/opt/FingerprintSecureDrop"
fpsd_crawler_git_repo_url: "https://github.com/freedomofpress/FingerprintSecureDrop"

# Username for running the crawler systemd service.
fpsd_crawler_system_account: fpsd
