---
crawler_apt_packages:
  - xvfb # tbs
  - git #tbs
  - gnupg-curl # needed for https keyservers
  - libfontconfig1 # tbb (firefox)
  - libxrender1 # tbb (firefox)
  - libasound2 # tbb (firefox)
  - libdbus-glib-1-2 # tbb (firefox)
  - libgtk2.0-0 # tbb (firefox)

tbb_arch: 64
tbb_release: 6.0.3
tbb_locale: en-US

tor_release: 0.2.8.6

entry_node: 1B60184DB9B96EA500A19C52D88F145BA5EC93CD

ssh_username: "{{ ansible_ssh_user }}"
