---
crawler_apt_packages:
  - xvfb # tbs
  - git #tbs
  - gnupg-curl # needed for https keyservers
  - libfontconfig1 # tbb (firefox)
  - libxrender1 # tbb (firefox)
  - libasound2 # tbb (firefox)
  - libdbus-glib-1-2 # tbb (firefox)
  - libgtk2.0-0 # tbb (firefox)

# Specify TBB version to download and install
tbb_release: 6.0.5
tbb_locale: en-US
tbb_arch: 64

# Specify Tor version to download, patch, build, and install
tor_release: 0.2.8.7

ssh_username: "{{ ansible_ssh_user }}"
