---
fpsd_common_apt_packages:
  - aptitude # needed by Ansible for apt 'upgrade'
  - python3-pip
  - python3.5
  - tmux
  - vim
  - libpq-dev # needed to install psycopg2

fpsd_common_pypi_packages:
  - pip
  - pytest
  - ipython
  - ipdb

fpsd_common_project_directory: "/usr/local/src/FingerprintSecureDrop"
fpsd_common_git_repo_url: "https://github.com/freedomofpress/FingerprintSecureDrop"
fpsd_crawler_apt_packages:
  - xvfb # tbs
  - git #tbs
  - gnupg-curl # needed for https keyservers
  - libfontconfig1 # tbb (firefox)
  - libxrender1 # tbb (firefox)
  - libasound2 # tbb (firefox)
  - libdbus-glib-1-2 # tbb (firefox)
  - libgtk2.0-0 # tbb (firefox)

# Specify TBB version to download and install
fpsd_crawler_tbb_release: 6.0.5
fpsd_crawler_tbb_locale: en-US
fpsd_crawler_tbb_arch: 64

# Specify Tor version to download, patch, build, and install
fpsd_crawler_tor_release: 0.2.8.7

ssh_username: "{{ ansible_user|default(ansible_ssh_user|default(lookup('env', 'USER'))) }}"

fpsd_common_project_directory: "/usr/local/src/FingerprintSecureDrop"
fpsd_common_git_repo_url: "https://github.com/freedomofpress/FingerprintSecureDrop"
