---
- name: Clobber relay.c in Tor {{ tor_release }} with custom relay.c from repo
  become: yes
  become_user: "{{ ssh_username }}"
  patch:
    src: relay.c.patch
    # Not using the ~username prefix to the fullpath because the patch module
    # doesn't expand the path correctly. Technically it's an assumption that
    # the user's home directory resides in /home/<username>, but a reasonable one.
    basedir: /home/{{ ssh_username }}/tbb/tor-{{ tor_release }}/src/or
  register: tor_relay_patch_result

- name: Configure Tor {{ tor_release }}
  become: yes
  become_user: "{{ ssh_username }}"
  command: ./configure
  args:
    chdir: "~{{ ssh_username }}/tbb/tor-{{ tor_release }}"
  when: tor_relay_patch_result|changed

- name: Make Tor {{ tor_release }}
  become: yes
  become_user: "{{ ssh_username }}"
  command: make
  args:
    chdir: "~{{ ssh_username }}/tbb/tor-{{ tor_release }}"
  when: tor_relay_patch_result|changed

- name: Install Tor {{ tor_release }}
  become: yes
  command: make install
  args:
    chdir: "~{{ ssh_username }}/tbb/tor-{{ tor_release }}"
  when: tor_relay_patch_result|changed

- name: Configure torrc disable entry guards
  become: yes
  lineinfile:
    dest: /usr/local/etc/tor/torrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
  with_items:
    - regexp: "^EntryNodes"
      line: "EntryNodes {{ entry_node }}"
    - regexp: "^ControlPort"
      line: "ControlPort 9051"
    - regexp: "^CookieAuthentication"
      line: "CookieAuthentication 1"

# We used to set `UseEntryGuards 0` in torrc. This is so this line will be
# removed when re-provision existing crawlers
- name: Remove UseEntryGuards line from torrc
  become: yes
  lineinfile:
    dest: /usr/local/etc/tor/torrc
    regexp: "^UseEntryGuards"
    state: absent

