---
- name: Clone git repository.
  become: yes
  become_user: "{{ ssh_username }}"
  git:
    repo: "{{ crawler_git_repo }}"
    dest: "{{ crawler_project_directory }}"
    force: yes
  # Under vagrant the project will be mounted as a shared directory,
  # so no need to clone it. Deploying to prod, however, means we'll need
  # to pull, so check the SSH username as a proxy for vagrant environment.
  when: ssh_username != 'vagrant'
