---
- block:

  - name: Create tbb directory.
    file:
      path: "{{ fpsd_crawler_tbb_directory }}"
      state: directory
      mode: 0755

  - name: Download TBB {{ fpsd_crawler_tbb_release }} tarball and signature.
    get_url:
      url: "{{ item }}"
      dest: "{{ fpsd_crawler_tbb_directory }}/{{ item|basename }}"
    with_items:
      - https://dist.torproject.org/torbrowser/{{ fpsd_crawler_tbb_release }}/tor-browser-linux{{ fpsd_crawler_tbb_arch }}-{{ fpsd_crawler_tbb_release }}_{{ fpsd_crawler_tbb_locale }}.tar.xz
      - https://dist.torproject.org/torbrowser/{{ fpsd_crawler_tbb_release }}/tor-browser-linux{{ fpsd_crawler_tbb_arch }}-{{ fpsd_crawler_tbb_release }}_{{ fpsd_crawler_tbb_locale }}.tar.xz.asc

  - name: Download TBB {{ fpsd_crawler_tbb_release }} signing key.
    become: yes
    command: gpg --keyserver hkps://keyserver.cns.vt.edu --recv-key EF6E286DDA85EA2A4BA7DE684E2C6E8793298290
    register: gpg_import_tor_browser_devs_key_result
    changed_when: "'imported: 1' in gpg_import_tor_browser_devs_key_result.stderr"

  - name: Verify TBB {{ fpsd_crawler_tbb_release }} signature.
    command: >
      gpg --verify
      tor-browser-linux{{ fpsd_crawler_tbb_arch }}-{{ fpsd_crawler_tbb_release }}_{{ fpsd_crawler_tbb_locale }}.tar.xz.asc
      tor-browser-linux{{ fpsd_crawler_tbb_arch }}-{{ fpsd_crawler_tbb_release }}_{{ fpsd_crawler_tbb_locale }}.tar.xz
    register: gpg_verify_result
    changed_when: false
    args:
      chdir: "{{ fpsd_crawler_tbb_directory }}"

  - name: Extract TBB {{ fpsd_crawler_tbb_release }} archive.
    unarchive:
      copy: no
      src: "{{ fpsd_crawler_tbb_directory }}/tor-browser-linux{{ fpsd_crawler_tbb_arch }}-{{ fpsd_crawler_tbb_release }}_{{ fpsd_crawler_tbb_locale }}.tar.xz"
      dest: "{{ fpsd_crawler_tbb_directory }}"

  become: yes
  become_user: "{{ fpsd_crawler_system_account }}"
