---
- name: Create Tor download directory.
  become: yes
  file:
    path: "{{ fpsd_crawler_tor_directory }}"
    state: directory
    owner: "{{ fpsd_crawler_system_account }}"
    group: "{{ fpsd_crawler_system_account }}"
    mode: "0755"

- block:
  - name: Download Tor {{ fpsd_crawler_tor_release }} source and signature.
    get_url:
      url: "{{ item }}"
      dest: "{{ fpsd_crawler_tor_directory }}/{{ item|basename }}"
    with_items:
      - https://dist.torproject.org/tor-{{ fpsd_crawler_tor_release }}.tar.gz
      - https://dist.torproject.org/tor-{{ fpsd_crawler_tor_release }}.tar.gz.asc

  - name: Download Tor {{ fpsd_crawler_tor_release }} signing key.
    command: gpg --keyserver hkps://keyserver.cns.vt.edu --recv-key B35BF85BF19489D04E28C33C21194EBB165733EA
    register: gpg_import_tor_browser_devs_key_result
    changed_when: "'imported: 1' in gpg_import_tor_browser_devs_key_result.stderr"

  - name: Verify Tor {{ fpsd_crawler_tor_release }} signature.
    command: >
      gpg --verify
      tor-{{ fpsd_crawler_tor_release }}.tar.gz.asc
      tor-{{ fpsd_crawler_tor_release }}.tar.gz
    register: gpg_verify_result
    changed_when: false
    args:
      chdir: "{{ fpsd_crawler_tor_directory }}"

  - name: Extract Tor {{ fpsd_crawler_tbb_release }} archive.
    unarchive:
      copy: no
      src: "{{ fpsd_crawler_tor_directory }}/tor-{{ fpsd_crawler_tor_release }}.tar.gz"
      dest: "{{ fpsd_crawler_tor_directory }}/"
      # Don't reextract on subsequent runs, since reextracting would needlessly
      # revert the custom patch to the relay.c file in subsequent tasks.
      creates: "{{ fpsd_crawler_tor_directory }}/tor-{{ fpsd_crawler_tor_release }}"

  become: yes
  become_user: "{{ fpsd_crawler_system_account }}"
