---
- name: Download Tor {{ fpsd_crawler_tor_release }} source and signature.
  become: yes
  become_user: "{{ ssh_username }}"
  get_url:
    url: "{{ item }}"
    dest: "~{{ ssh_username }}/tbb/{{ item|basename }}"
  with_items:
    - https://dist.torproject.org/tor-{{ fpsd_crawler_tor_release }}.tar.gz
    - https://dist.torproject.org/tor-{{ fpsd_crawler_tor_release }}.tar.gz.asc

- name: Download Tor {{ fpsd_crawler_tor_release }} signing key.
  become: yes
  become_user: "{{ ssh_username }}"
  command: gpg --keyserver hkps://keyserver.cns.vt.edu --recv-key B35BF85BF19489D04E28C33C21194EBB165733EA
  register: gpg_import_tor_browser_devs_key_result
  changed_when: "'imported: 1' in gpg_import_tor_browser_devs_key_result.stderr"

- name: Verify Tor {{ fpsd_crawler_tor_release }} signature.
  become: yes
  become_user: "{{ ssh_username }}"
  command: gpg --verify tor-{{ fpsd_crawler_tor_release }}.tar.gz.asc tor-{{ fpsd_crawler_tor_release }}.tar.gz
  register: gpg_verify_result
  changed_when: false
  args:
    chdir: "~{{ ssh_username }}/tbb/"

- name: Extract Tor {{ fpsd_crawler_tbb_release }} archive.
  become: yes
  become_user: "{{ ssh_username }}"
  unarchive:
    copy: no
    src: "~{{ ssh_username }}/tbb/tor-{{ fpsd_crawler_tor_release }}.tar.gz"
    dest: "~{{ ssh_username }}/tbb/"
    # Don't reextract on subsequent runs, since reextracting would needlessly
    # revert the custom patch to the relay.c file in subsequent tasks.
    creates: "~{{ ssh_username }}/tbb/tor-{{ fpsd_crawler_tor_release }}"
