---
- name: Clone git repository.
  become: yes
  git:
    repo: "{{ fpsd_common_git_repo_url }}"
    dest: "{{ fpsd_common_project_directory }}"
    force: yes
  # Under vagrant the project will be mounted as a shared directory,
  # so no need to clone it. Deploying to prod, however, means we'll need
  # to pull, so check the SSH username as a proxy for vagrant environment.
  # The Xenial image uses "ubuntu" as default SSH user, so check that as
  # well as the more common "vagrant" username.
  when: ssh_username not in ['vagrant', 'ubuntu']
