---
- name: Install common packages.
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
      # No need to update package cache because we do this in
      # update-packages.yml
    update_cache: no
  with_items: "{{ common_apt_packages }}"

- name: Set tmux mode to vim, avoid that rsi.
  become: yes
  become_user: "{{ ssh_username }}"
  lineinfile:
    dest: "~/.tmux.conf"
    line: "setw -g mode-keys vi"
    create: yes
