---
- name: Add Deadsnakes PPA for python3.5
  become: yes
  apt_repository:
    repo: "ppa:fkrull/deadsnakes"
    update_cache: yes

- name: Install python3.5
  become: yes
  apt:
    name: python3.5
    state: latest
  with_items:
    - python3.5
    - python3-pip

# This is necessary so that later the Ansible pip module will dependencies to
# the python3.5 and not python3.4 dist-package directory
- name: Set python3.5 as default python3 alternative
  become: yes
  command: update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
