---
- name: Install and upgrade Python packaging and debugging tools.
  become: true
  pip:
    executable: pip3
    name: "{{ item }}"
    state: latest
  with_items: "{{ fpsd_common_pypi_packages }}"
