---
- name: Install common packages.
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    # Only update if it's been 24 hours since last time
    cache_valid_time: 86400
  with_items: "{{ fpsd_common_apt_packages }}"

- name: Install and upgrade Python packaging and debugging tools.
  become: true
  pip:
    executable: pip3
    name: "{{ item }}"
    state: latest
  with_items: "{{ fpsd_common_pypi_packages }}"
