---
- name: Install aptitude (needed by ansible).
  become: yes
  apt:
    name: aptitude
    state: present
    update-cache: yes
    cache_valid_time: 86400

# - name: Install sid repo
#   become: yes
#   apt_repository:
#     repo: "deb http://ftp.us.debian.org/debian/ sid main"
#     update_cache: yes

- name: Upgrade all packages.
  become: yes
  apt:
    upgrade: safe
    update_cache: yes
    # Only update if it's been 24 hours since last time
    cache_valid_time: 86400
