---
- name: Configure FingerprintSecureDrop Tor Hidden Service crawler.
  hosts: localhost
  roles:
    - role: ../roles/crawler
      fpsd_database_usernames: travis
      fpsd_crawler_clone_git_repo: false
      fpsd_crawler_system_account: travis
      fpsd_crawler_project_directory: "/home/travis/build/freedomofpress/FingerprintSecureDrop"
