---
- name: Configure FingerprintSecureDrop Tor Hidden Service crawler.
  hosts: all
  roles:
    - role: ../roles/crawler
      fpsd_crawler_clone_git_repo: false # don't clone, use mounted local directory
      fpsd_crawler_system_account: vagrant
      tags: crawler
  tasks:
    - name: Set tmux mode to vim, avoid that rsi.
      become: yes
      lineinfile:
        dest: "/etc/tmux.conf"
        line: "setw -g mode-keys vi"
        create: yes
        owner: root
        group: root
        mode: "0644"
