---
- name: Install sorter.py pip dependencies.
  become: yes
  pip:
    executable: pip3
    state: latest
    requirements: "~{{ ssh_username }}/FingerprintSecureDrop/fpsd/requirements/sorter-requirements.txt"
