---
- name: Install hs-sorter pip dependencies to hs-sorter virtualenv.
  pip:
    chdir: "~{{ ssh_username }}/FingerprintSecureDrop"
    requirements: "sorter-requirements.txt"
    executable: "~{{ ssh_username }}/FingerprintSecureDrop/bin/pip"
    virtualenv_python: python3.5
    virtualenv: "~{{ ssh_username }}/FingerprintSecureDrop"
