---
- name: Install hs-sorter pip dependencies to hs-sorter virtualenv.
  pip:
    requirements: "sorter-requirements.txt"
    chdir: "~{{ ssh_username }}/FingerprintSecureDrop"
    executable: /usr/bin/pip3
    virtualenv: "~{{ ssh_username }}/FingerprintSecureDrop"
    virtualenv_python: /usr/bin/python3.5
